[tool.poetry]
name = "streamlit-inspector"
version = "0.1.1"
description = "ğŸ•µï¸ Streamlit component to inspect Python objects during development"
authors = ["Johannes Rieke <johannes.rieke@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
streamlit = "^1.6.0"
validators = "^0.18.2"
Pygments = "^2.11.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
watchdog = "^2.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
